// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnGR63WJPZy1xHbqsU6jZcmnhzgMEGjs',
    appId: '1:21234920257:web:f8ddbb140dd8202a9c4fc0',
    messagingSenderId: '21234920257',
    projectId: 'tractalk-4e2d8',
    authDomain: 'tractalk-4e2d8.firebaseapp.com',
    storageBucket: 'tractalk-4e2d8.firebasestorage.app',
    measurementId: 'G-JQ58E0TLD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7PtS-djic-Vufu6YjCZVHmyB7ZJUMgaw',
    appId: '1:21234920257:android:f9254c57ef8d1f2e9c4fc0',
    messagingSenderId: '21234920257',
    projectId: 'tractalk-4e2d8',
    storageBucket: 'tractalk-4e2d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL0KdKvZfoUgNBB-8VniKH5PsqN0OhWTQ',
    appId: '1:21234920257:ios:78952cef2296cf879c4fc0',
    messagingSenderId: '21234920257',
    projectId: 'tractalk-4e2d8',
    storageBucket: 'tractalk-4e2d8.firebasestorage.app',
    iosBundleId: 'com.linblink.tractalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnGR63WJPZy1xHbqsU6jZcmnhzgMEGjs',
    appId: '1:21234920257:web:07b2ee4b4d2befa79c4fc0',
    messagingSenderId: '21234920257',
    projectId: 'tractalk-4e2d8',
    authDomain: 'tractalk-4e2d8.firebaseapp.com',
    storageBucket: 'tractalk-4e2d8.firebasestorage.app',
    measurementId: 'G-3VY3LDMFQ6',
  );
}
